### ISSUE TITLE
Ios-discord-blueberry not opening with xcode

### ISSUE THREAD

**Issue by crceck123** [CatsLover2006/2048#1]
![IMG_20221226_070530_612](https://user-images.githubusercontent.com/100026828/209494686-ec672682-d583-4ddf-970c-229b3a83ffee.jpg)

**Comment by CatsLover2006** [comment]
That project is an archive, I no longer maintain it (in fact, the source on my computer was lost as I accidentally wiped the drive). Good luck.

**Comment by crceck123** [comment]
> That project is an archive, I no longer maintain it (in fact, the source on my computer was lost as I accidentally wiped the drive). Good luck.

And in what version xcode did you open that blueberry?

**Comment by CatsLover2006** [comment]
It was the one you can download on Mountain Lion, can't remember the version number.
